language: R
sudo: false
warnings_are_errors: false
cache: packages

before_deploy:
  - R -e "install.packages('roxygen2', repos = 'http://cran.rstudio.com')"

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'